### ISSUE TITLE
Depends on broken generic_array

### ISSUE THREAD

**Issue by RalfJung** [NeoBirth/PureZen#19]
This is a heads-up that this crate depends on a buggy version of generic_array that does not contain https://github.com/fizyk20/generic-array/issues/89, and https://github.com/rust-lang/rust/pull/71274 means that in future rustc versions this can lead to panics when using old generic_array. Would be great if you could update the dependency. :)

**Comment by riking** [comment]
The panics in the future: https://asan.saethlin.dev/ub?crate=purezen&version=0.0.2

**Comment by tarcieri** [comment]
This project doesn't really work, and it's dead. I'm going to close all of the issues and archive it.
