### ISSUE TITLE
Where to start for contribution

### ISSUE THREAD

**Issue by ales-tsurko** [NeoBirth/PureZen#20]
Hi! I'd like to continue developing this project. Could you point me where to start and what's the state of it? Also, could you share your (unfinished) ideas related to the implementation of this crate? Though, I'm not sure about `no-std` as it's out of scope for my requirements... But I'd make a fork or something and I'd maybe continue it with `no-std`. Not sure until I didn't dive into the code. Anyway, I'd started from [bindings for ZenGarden](https://github.com/miller-app/miller/tree/main/miller-engine), but now I can spend more time on this project and would rather continue Rust implementation.

**Comment by tarcieri** [comment]
I basically abandoned this project. Translating ZenGarden turned into quite the chore, especially with aspirations of making it `no_std`-friendly.

ZenGarden heavily utilizes inheritance, which maps poorly to Rust.

It was also quite difficult to get to a working core implementation, as the internal structure of ZenGarden is heavily inter-related. Without being able to get to a working, tested spike and iterating, I felt like I was probably making translation errors all over the place. And in the end it was just taking up too much time and I moved on to other things.

If you're generally interested in Rust Audio, I'd suggest hopping on https://rust-audio.discourse.group/

There are now other options for DSP engines, although I'm not sure any of them support pD per se.

**Comment by ales-tsurko** [comment]
I see. Thanks!
